---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jhn.
--- DateTime: 2023/4/20 20:38
---
if(redis.call("get",KEYS[1]) == ARGV[1]) then
    return redis.call("del",KEYS[1])
end
return 0